---
title: "circle2 and friends"
format: 
  html:
    embed-resources: true
---

This program was written by Steve Simon on 2026-04-29 and is placed in the public domain (CC0).

```{r}
#| label: setup
#| message: false
#| warning: false

library(tidyverse)
```

## circle2

The circleFun function is found at Stack Overflow

https://stackoverflow.com/questions/6862742/draw-a-circle-with-ggplot2

Also see 

https://ggplot2.tidyverse.org/reference/geom_tile.html

https://www.jstor.org/stable/24976032


```{r}
#| fig.width: 7
#| fig.height: 7

w <- 100

draw_circles <- function(w=100) {
  w <- 100/sqrt(w)
  x <- rep(-100:100, 201) / w
  y <- rep(-100:100, each=201) / w
  r <- (x^2 + y^2)
  z <- r %% 2 + 1
  z <- c("black", "white")[z]
  z[r > (100/w)^2] <- "white"

  n <- floor(100^2/w)

  data.frame(x, y, z) |>
    ggplot() +
    aes(x=x, y=y) +
    geom_raster(fill=z) +
    # geom_label(x=0, y=0, label=n) +
    theme_void() -> p
  
  print(w)
  print(p)
  
  file_name <- paste0("p", str_pad(w, width=3, pad="0"), ".png")
  ggsave(file_name, width=201, height=201, unit="px")
}

for (w in 1:100) {draw_circles(w)}
```



