---
title: "The AB/BA cross-over"
editor: source
---

```{r}
#| label: 02-setup
#| message: false
#| warning: false

library(broom)
library(lme4)
library(tidyverse)
```

## Read

```{r}
#| label: 02-read

asthma_1 <- read_table(
  file="../data/asthma_1.txt",
  col_names=TRUE,
  col_types="ncnn")

asthma_2 <- read_table(
  file="../data/asthma_2.txt",
  col_names=TRUE,
  col_types="ncnn")

asthma_2 |>
  pivot_longer(
    cols=c(formoterol, salbutamol),
    names_to="treatment",
    values_to="pef") -> asthma_3
```


## Paired t-test

```{r}
#| label: 02-paired

t.test(
  asthma_2$formoterol, 
  asthma_2$salbutamol,
  paired=TRUE)
```

## Recalculate confidence interval with z instead of t

```{r}
#| label: 02-recalculate

asthma_2 |>
  mutate(treatment_difference=formoterol-salbutamol) |>
  summarize(
    difference_mean=mean(treatment_difference),
    difference_stdev=sd(treatment_difference),
    n=n()) |>
  mutate(
    lower=difference_mean-1.96*difference_stdev/sqrt(n),
    upper=difference_mean+1.96*difference_stdev/sqrt(n))
```

## Alternate form of paired t-test

```{r}
#| label: 02-alternate-1

m3 <- lm(pef ~ treatment + factor(id), data=asthma_3)
confint(m3)[2, ]
```

## Second alternate form

```{r}
#| label: 02-alternative-paired

m2 <- lmer(pef~treatment+(1|id), data=asthma_3) 
summary(m2)
fixef(m2)
confint(m2, parm="treatmentsalbutamol", method="Wald")

```
