---
title: "circle2 and friends"
format: 
  html:
    embed-resources: true
---

This program was written by Steve Simon on 2026-04-29 and is placed in the public domain (CC0).

```{r}
#| label: setup
#| message: false
#| warning: false

library(gifski)
library(tidyverse)

n_images <- 900
step_size <- 0.2
```

## circle2

The circleFun function is found at Stack Overflow

https://stackoverflow.com/questions/6862742/draw-a-circle-with-ggplot2

Also see 

https://ggplot2.tidyverse.org/reference/geom_tile.html

https://www.jstor.org/stable/24976032


```{r}
#| fig.width: 7
#| fig.height: 7
#| eval: true

circle_files <- sprintf("../images/circle%04d.png", 1:n_images)

draw_circles <- function(w, k) {
  x <- rep(-100:100, 201) / 100
  y <- rep(-100:100, each=201) / 100
  r <- x^2 + y^2
  z <- (r*w) %% 2 + 1
  n_circles <- ceiling(max(r*w)/2-0.2)
  # max(floor(r*w)) %/% 2

  z <- c("black", "white")[z]

  data.frame(x, y, z) |>
    ggplot() +
    aes(x=x, y=y) +
    geom_raster(fill=z) +
    labs(title=n_circles) +
    # geom_label(x=0, y=0, label=n) +
    theme_void() -> p
  
  file_name <- paste0(
    "../images/circle", 
    str_pad(k, width=4, pad="0"),
    ".png")
  file_name <- sprintf("../images/circle%04d.png", k)
  ggsave(circle_files[k], width=201, height=301, unit="px")
}

for (k in 1:n_images) {
  w <- 1 + (k-1)*step_size
  draw_circles(w, k)
  cat(k)
  cat(" ")
}

gif_file <- "circle_animation.gif"
gifski(
  circle_files, 
  gif_file,
  delay=0.03,
  loop=FALSE)
# utils::browseURL(gif_file)
```

```{r}
#| fig.width: 7
#| fig.height: 7

diamond_files <- sprintf("../images/diamond%04d.png", 1:n_images)

draw_diamonds <- function(w, k) {
  x <- rep(-100:100, 201) / 100
  y <- rep(-100:100, each=201) / 100
  r <- abs(x)*w + abs(y)*w
  z <- r^2 %% 2 + 1
  n_diamonds <- ceiling(max(r^2)/2-0.2)

  z <- c("black", "white")[z]

  data.frame(x, y, z) |>
    ggplot() +
    aes(x=x, y=y) +
    geom_raster(fill=z) +
    labs(title=n_diamonds) +
    # geom_label(x=0, y=0, label=n) +
    theme_void() -> p
  
  ggsave(
    diamond_files[k], 
    width=201, 
    height=301, 
    unit="px")
}

for (k in 1:n_images) {
  w <- 1 + 9*(k-1)/(n_images-1)
  draw_diamonds(w, k)
  cat(k)
  cat(" ")
}

gif_file <- "diamond_animation.gif"
gifski(
  diamond_files, 
  gif_file,
  delay=0.03,
  loop=FALSE)
# utils::browseURL(gif_file)
```

```{r}
n <- 21
co <- c("white", "black")[1+(1:n)%%2]
data.frame(
  x1=seq(1, 0, length=n), 
  y1=rep(0, n), 
  x0=rep(0, n),
  y0=seq(1, 0, length=n)^0.5) |>
  ggplot() +
  aes(x=x0, y=y0, xend=x1, yend=y1) |>
  geom_segment(color=co) +
  theme(aspect.ratio=1) + 
  scale_x_continuous(breaks=(0:10)/10) +
  scale_y_continuous(breaks=(0:10)/10)
```

$y=\sqrt{x}-\sqrt{x}*x$

$y=\sqrt{x}*(1-x)$


```{r}
#| fig.width: 2
#| fig.height: 2

n <- 1001
a <- seq(-1, 1, length=n)
d <- data.frame(
  x=rep(a, n),
  y=rep(a, each=n))

w <- 1
r <- w *(d$x+d$y)

irregular_diamonds <- function(x, y, n) {
  r <- 0
  for (i in 0:n) {
    r <- r + (abs(y) - (0.5^(i/2)*(1-2^i*abs(d$x))) < 0)
  }
  return(r)
}

r4 <- (abs(d$y) - (0.5^(4/2)*(1-2^4*abs(d$x))) < 0)
r3 <- (abs(d$y) - (0.5^(3/2)*(1-2^3*abs(d$x))) < 0)
r2 <- (abs(d$y) - (0.5^(2/2)*(1-2^2*abs(d$x))) < 0)
r1 <- (abs(d$y) - (0.5^(1/2)*(1-2^1*abs(d$x))) < 0)
r0 <- (abs(d$y) - (0.5^(0/2)*(1-2^0*abs(d$x))) < 0)

r <- (r0+r1+r2+r3+r4)

r <- irregular_diamonds(d$x, d$y, 16)

co <- c("white", "black")[1 + r%%2]
ggplot(d) +
  aes(x, y) +
  theme_void() +
  geom_raster(fill=co)
```

```{r}
n <- 5

bw <- c("black", "white")
wb <- rev(bw)

co <- wb[1+(1:n)%%2]
data.frame(
  x0=seq(0, 1, length=n)^0.5, 
  y0=rep(0, n), 
  x1=rep(0, n),
  y1=seq(0, 1, length=n)) |>
  ggplot() +
  aes(x=x0, y=y0, xend=x1, yend=y1) |>
  geom_segment(color=co) +
  theme(aspect.ratio=1) + 
  scale_x_continuous(breaks=(0:10)/10) +
  scale_y_continuous(breaks=(0:10)/10)
```
$y=x-x^{0.5}*x$

$y=x*(1-x^{0.5})$

```{r}
#| fig.width: 2
#| fig.height: 2

n <- 1001
a <- seq(-1, 1, length=n)
d <- data.frame(
  x=rep(a, n),
  y=rep(a, each=n))

x <- d$x
y <- d$y

r <- abs(y)/abs(0.5 - sqrt(0.5)*abs(x))

co <- c("white", "black")[1 + (r <= 1)]
ggplot(d) +
  aes(x, y) +
#  theme_void() +
  geom_raster(fill=co)
```